from django.conf.urls import patterns, url
from theses_sys.views import *

urlpatterns = patterns('',
	url(r'^$', browse.index.IndexView.as_view(), name='index'),
	url(r'^home/$', browse.home.HomeView.as_view(), name='home'),
	url(r'^login/$', session.login.LoginView.as_view(), name='login'),
	url(r'^logout/$', session.logout.LogoutView.as_view(), name='logout'),
	url(r'^admin/$', admin.accounts.AccountsView.as_view(), name='admin'),
	url(r'^add-entry/$', thesis.add.AddEntryView.as_view(), name='add-entry'),
	url(r'^create-entry/$', thesis.create.CreateEntryView.as_view(), name='create-entry'),
	url(r'^set-profile/$', account.edit.SetAccountView.as_view(), name='set-profile'),
	url(r'^update-profile/$', account.update.UpdateAccountView.as_view(), name='update-profile'),
	url(r'^generate-accounts/$', admin.generate.GenerateAccountsView.as_view(), name='generate-accounts'),
	url(r'^print-account/(?P<acct_id>\d+)/$', admin.printone.PrintAccountView.as_view(), name='print-account'),
	url(r'^print-accounts/$', admin.printbulk.PrintAccountsView.as_view(), name='print-accounts'),
	url(r'^delete-account/(?P<acct_id>\d+)/$', admin.delete.DeleteAccountView.as_view(), name='delete-account'),
	url(r'^delete-accounts/$', admin.delbulk.DeleteAccountsView.as_view(), name='delete-accounts'),
	url(r'^redirect-to-search/$', browse.redirect.SearchRedirectView.as_view(), name='redirect-to-search'),
	url(r'^search/(?P<filter>[a-zA-Z0-9_\- ]+)/(?P<query>[a-zA-Z0-9_\- ]+)/$', browse.search.SearchView.as_view(), name='search'),
	url(r'^my-domain/$', browse.session.SessionThesesView.as_view(), name='session-theses'),
	url(r'^getting-started/$', session.create.CreateSessionView.as_view(), name='create-user-session'),
	url(r'^department-theses/(?P<department_id>\d+)/$', browse.department.DepartmentThesesView.as_view(), name='department-theses'),
	url(r'^faculty-theses/(?P<username>\w+)/$', browse.faculty.FacultyThesesView.as_view(), name='faculty-theses'),
	url(r'^thesis/(?P<slug>[a-zA-Z0-9_\-]+)/$', thesis.show.ThesisView.as_view(), name='thesis'),
	url(r'^delete-entry/(?P<thesis_id>\d+)/$', thesis.delete.DeleteEntryView.as_view(), name='delete-entry'),
	url(r'^edit-entry/(?P<thesis_id>\d+)/$', thesis.edit.EditEntryView.as_view(), name='edit-entry'),
	url(r'^update-entry/(?P<thesis_id>\d+)/$', thesis.update.UpdateEntryView.as_view(), name='update-entry'),
)