application: browseuptheses
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: django
  version: "1.5"

builtins:
- django_wsgi: on

handlers:
- url: /static/theses_sys
  static_dir: static/theses_sys
  expiration: '0'

env_variables:
  DJANGO_SETTINGS_MODULE: 'browseuptheses.settings'